const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('stemStudio', {
  pickInput: () => ipcRenderer.invoke('pick-input'),
  pickOutput: () => ipcRenderer.invoke('pick-output'),
  pickEngine: () => ipcRenderer.invoke('pick-engine'),
  pickDefaultOutput: () => ipcRenderer.invoke('pick-default-output'),
  clearEngine: () => ipcRenderer.invoke('clear-engine'),
  clearDefaultOutput: () => ipcRenderer.invoke('clear-default-output'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  setSettings: (patch) => ipcRenderer.invoke('set-settings', patch),
  engineStatus: () => ipcRenderer.invoke('engine-status'),
  stemOptions: () => ipcRenderer.invoke('stem-options'),
  getHistory: () => ipcRenderer.invoke('get-history'),
  clearHistory: () => ipcRenderer.invoke('clear-history'),
  getQueue: () => ipcRenderer.invoke('get-queue'),
  start: (options) => ipcRenderer.invoke('start-separation', options),
  cancel: () => ipcRenderer.invoke('cancel-separation'),
  cancelJob: (id) => ipcRenderer.invoke('cancel-job', id),
  retryJob: (id) => ipcRenderer.invoke('retry-job', id),
  openPath: (target) => ipcRenderer.invoke('open-path', target),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  appVersion: () => ipcRenderer.invoke('app-version'),
  checkForUpdate: () => ipcRenderer.invoke('check-for-update'),
  mediaStatus: () => ipcRenderer.invoke('media-status'),
  mediaInstall: () => ipcRenderer.invoke('media-install'),
  onMediaProgress: (listener) => ipcRenderer.on('media-progress', (_event, data) => listener(data)),
  modelsStatus: () => ipcRenderer.invoke('models-status'),
  modelDownload: (name) => ipcRenderer.invoke('model-download', name),
  modelDownloadCancel: (name) => ipcRenderer.invoke('model-download-cancel', name),
  modelImport: (name) => ipcRenderer.invoke('model-import', name),
  onModelProgress: (listener) => ipcRenderer.on('model-progress', (_event, data) => listener(data)),
  listStems: (dir) => ipcRenderer.invoke('list-stems', dir),
  readAudioFile: (filePath) => ipcRenderer.invoke('read-audio-file', filePath),
  exportMix: (payload) => ipcRenderer.invoke('export-mix', payload),
  pathForFile: (file) => webUtils.getPathForFile(file),
  onUpdate: (listener) => ipcRenderer.on('separation-update', (_event, data) => listener(data)),
  onQueueUpdate: (listener) => ipcRenderer.on('queue-update', (_event, data) => listener(data)),
  onQueueFinished: (listener) => ipcRenderer.on('queue-finished', (_event, data) => listener(data))
});
